### ISSUE TITLE
Consider archiving this repository ?

### ISSUE THREAD

**Issue by Chromosore** [juliushaertl/libcloudproviders#1]
I saw that this repository was now maintained on the GNOME gitlab, so I think you should archive this repository and put a link pointing to the gitlab repository.

I'm just saying this to help new people to find the gitlab repository as googling "libcloudprovider" yields this repository first.

**Comment by juliusknorr** [comment]
Makes senes 👍 

Added a note with the link to the Readme and will archive it.

Thanks for reaching out.
